### ISSUE TITLE
Hello, I have a issues when I run multi robots exploration.

### ISSUE THREAD

**Issue by Gaoee** [hasauino/rrt_exploration#2]
Hello, I have a issues when run multi robots exploration.
![image](https://github.com/Gaoee/image/blob/master/Screenshot%20from%202018-04-10%2015-01-08.png)
The merged map is not a properly position. And When launch "mutliple_simulated_largeMap.launch", there is always show an error about " not transfer from "word" to "robot1/map" ".

**Comment by hasauino** [comment]
Try this fork: https://github.com/hasauino/m-explore/tree/master/map_merge

This fork is an older version of the map_merge package. The older version used to work fine.

**Comment by Gaoee** [comment]
Yes, this work for me. Thank you!
But I have another question as follow image show, there is not appear many RRT tree lines as the video show. 
![image](https://github.com/Gaoee/image/blob/master/Screenshot%20from%202018-04-10%2015-58-42.png)
What can do for it. Thanks.

**Comment by sandilyasg** [comment]
@Gaoee  @hasauino How do you run the multi robot rrt_exploration? I am using ROS melodic. These are my steps:
`roslaunch rrt_exploration_tutorials multiple_simulated_house.launch`
`roslaunch rrt_exploration_tutorials map_merge.launch`
`roslaunch rrt_exploration three_robots.launch`

When I run`roslaunch rrt_exploration three_robots.launch` I get the following error:

```
[ERROR] [1677001900.306743, 2623.350000]: bad callback: <function globalMap at 0x7feec434ccd0>
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/sgari/iral_research/sim_rrt_ws/src/rrt_exploration/scripts/filter.py", line 42, in globalMap
    [litraIndx])-namespace_init_count
ValueError: invalid literal for int() with base 10: '_'

[ERROR] [1677001900.308289, 2623.420000]: bad callback: <function globalMap at 0x7feec434ccd0>
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/-/iral_research/sim_rrt_ws/src/rrt_exploration/scripts/filter.py", line 42, in globalMap
    [litraIndx])-namespace_init_count
ValueError: invalid literal for int() with base 10: '_'
```
